- name: Get instance type from metadata
  uri:
    url: http://169.254.169.254/latest/meta-data/instance-type
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: instance_type

- name: Create list of mounted devices
  set_fact:
    mounted_devices: "{{ ansible_mounts|json_query('[].device') }}"

- name: Create a ext4 filesystem on all ephemeral volumes
  filesystem:
    fstype: ext4
    dev: "{{ item['device_name'] }}"
  loop: "{{ volumes }}"
  when: item['device_name'] not in mounted_devices

# TODO: create raid setups for multi-volume instance stores

- name: Mount
  mount:
    path: "{{ mount_path }}"
    src: "{{ volumes[0]['device_name'] }}"
    fstype: ext4
    state: mounted
  when: volumes|length == 1
