---
# tasks file for cloud-helper

- name: check if running on cloud
  stat:
    path: /var/lib/cloud
  register: cloud

- name: Wait for updates / upgrades from user data script to release lock
  script: wait-for-apt-on-startup.sh
  when: cloud.stat.exists and enable_cloud_wait

- name: Install JQ
  apt:
    name: jq
    state: present
    update_cache: yes
  when: enable_jq

- name: Get instance type from metadata
  uri:
    url: curl http://169.254.169.254/latest/meta-data/instance-type
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: instance_type

- name: Create list of mounted devices
  set_fact:
    mounted_devices: "{{ ansible_mounts|json_query('[].device') }}"

- name: Create a ext4 filesystem on all ephemeral volumes
  filesystem:
      fstype: ext4
      dev: "{{ item['device_name'] }}"
  loop: "{{ volumes }}"
  when: item['device_name'] not in mounted_devices

# TODO: create raid setups for multi-volume instance stores

- name: Mount
  mount:
    path: "{{ mount_path }}"
    src: "{{ volumes[0]['device_name'] }}"
    fstype: ext4
    state: mounted
  when: volumes|length == 1
